# Generated by Django 5.0.4 on 2026-09-08 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandprofile',
            name='company_description',
            field=models.TextField(blank=True, help_text='Core services, background, or brochure text'),
        ),
        migrations.AddField(
            model_name='brandprofile',
            name='website_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
