# Generated by Django 5.0.4 on 2026-09-08 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_brandprofile_company_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedpost',
            name='media_urls',
            field=models.JSONField(blank=True, default=list, help_text='List of image URLs for carousel posts'),
        ),
    ]
