# Generated by Django 5.2.17 on 2026-09-16 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_generatedpost_media_urls'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_campaign_id', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_adset_id', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_ad_id', models.CharField(blank=True, max_length=255, null=True)),
                ('budget', models.DecimalField(decimal_places=2, default=10.0, help_text='Daily budget in account currency', max_digits=10)),
                ('status', models.CharField(default='PENDING', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ad_campaign', to='core.generatedpost')),
            ],
        ),
        migrations.CreateModel(
            name='AutoReplySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_text', models.TextField(blank=True, help_text='The text to auto-reply to comments on Facebook and Instagram.')),
                ('is_active', models.BooleanField(default=False)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auto_reply_settings', to='core.business')),
            ],
        ),
    ]
