# Generated by Django 5.0.4 on 2026-09-17 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_adcampaign_autoreplysettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedpost',
            name='published_platform',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
