# Generated by Django 5.0.4 on 2026-09-18 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_generatedpost_published_platform'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoReplyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(help_text='facebook or instagram', max_length=50)),
                ('commenter_name', models.CharField(blank=True, max_length=255, null=True)),
                ('comment_text', models.TextField(blank=True, null=True)),
                ('reply_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_reply_logs', to='core.business')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
