# Generated by Django 5.0.4 on 2026-09-22 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_autoreplylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedpost',
            name='category',
            field=models.CharField(blank=True, help_text='Category of the content (e.g. Product, Service, Event)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='generatedpost',
            name='fb_objective',
            field=models.CharField(blank=True, help_text='Objective for Facebook', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='generatedpost',
            name='insta_objective',
            field=models.CharField(blank=True, help_text='Objective for Instagram', max_length=255, null=True),
        ),
    ]
