# Generated by Django 5.0.4 on 2026-09-22 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_generatedpost_category_generatedpost_fb_objective_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandprofile',
            name='default_category',
            field=models.CharField(blank=True, help_text='Default category for generated posts', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='brandprofile',
            name='default_fb_objective',
            field=models.CharField(blank=True, help_text='Default objective for Facebook', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='brandprofile',
            name='default_insta_objective',
            field=models.CharField(blank=True, help_text='Default objective for Instagram', max_length=255, null=True),
        ),
    ]
