# Generated by Django 5.0.4 on 2026-09-22 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_brandprofile_default_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandprofile',
            name='liked_posts',
            field=models.TextField(blank=True, help_text='Examples of posts the user has approved, for AI to learn from'),
        ),
        migrations.AddField(
            model_name='generatedpost',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
