# Generated by Django 5.0.4 on 2026-09-22 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_brandprofile_liked_posts_generatedpost_scheduled_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandprofile',
            name='topics',
            field=models.TextField(blank=True, help_text='Configured topics for content generation', null=True),
        ),
    ]
