# Generated by Django 5.2.17 on 2026-09-23 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_brandprofile_topics'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoreplysettings',
            name='fb_dm_on_like_active',
            field=models.BooleanField(default=False, help_text='Enable auto-DM when someone likes your Facebook post'),
        ),
        migrations.AddField(
            model_name='autoreplysettings',
            name='fb_dm_text',
            field=models.TextField(blank=True, help_text='DM text to send to users who like your Facebook posts'),
        ),
        migrations.AddField(
            model_name='autoreplysettings',
            name='ig_dm_on_like_active',
            field=models.BooleanField(default=False, help_text='Enable auto-DM when someone likes your Instagram post'),
        ),
        migrations.AddField(
            model_name='autoreplysettings',
            name='ig_dm_text',
            field=models.TextField(blank=True, help_text='DM text to send to users who like your Instagram posts'),
        ),
        migrations.CreateModel(
            name='AutoDMLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(help_text='facebook or instagram', max_length=50)),
                ('trigger_type', models.CharField(default='like', help_text='What triggered the DM (e.g. like)', max_length=50)),
                ('recipient_name', models.CharField(blank=True, max_length=255, null=True)),
                ('recipient_id', models.CharField(blank=True, max_length=255, null=True)),
                ('dm_text', models.TextField(blank=True, null=True)),
                ('post_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(default='sent', help_text='sent or failed', max_length=50)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_dm_logs', to='core.business')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
