# Generated by Django 5.2.17 on 2026-09-23 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_autoreplysettings_fb_dm_on_like_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoreplysettings',
            name='fb_auto_reply_active',
            field=models.BooleanField(default=False, help_text='Enable auto-reply to Facebook comments'),
        ),
        migrations.AddField(
            model_name='autoreplysettings',
            name='fb_reply_text',
            field=models.TextField(blank=True, help_text='Auto-reply text for Facebook comments'),
        ),
        migrations.AddField(
            model_name='autoreplysettings',
            name='ig_auto_reply_active',
            field=models.BooleanField(default=False, help_text='Enable auto-reply to Instagram comments'),
        ),
        migrations.AddField(
            model_name='autoreplysettings',
            name='ig_reply_text',
            field=models.TextField(blank=True, help_text='Auto-reply text for Instagram comments'),
        ),
    ]
