# Generated by Django 5.0.4 on 2026-09-26 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_autoreplysettings_fb_auto_reply_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoreplylog',
            name='post_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
