# Generated by Django 5.0.4 on 2026-09-26 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_autoreplylog_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='autodmlog',
            name='comment_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
