# Generated by Django 5.2.17 on 2026-10-03 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_autodmlog_comment_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adcampaign',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_campaigns', to='core.generatedpost'),
        ),
    ]
