# Generated by Django 5.2.17 on 2026-10-03 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_adcampaign_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='adcampaign',
            name='campaign_type',
            field=models.CharField(default='BOOST', max_length=20),
        ),
    ]
